# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on: push
#on:  fork 

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt-hotspot'
        server-id: github 
        settings-path: ${{ github.workspace }} 

    - name: Build with Maven
      run: mvn -B package --file follow-coin-compute/pom.xml -Dmaven.test.skip=false
    - uses: actions/upload-artifact@v4
      with:
        path: /home/runner/work/follow-coin/follow-coin/follow-coin-compute/target/follow-coin-collect-0.0.1-SNAPSHOT.jar

  build-image:
        runs-on: ubuntu-latest
        needs: build

        steps:

          - uses: actions/checkout@v3

          - uses: actions/download-artifact@master
            with:
            #name: jar-file
              path: follow-coin-collect-0.0.1-SNAPSHOT.jar

          - uses: mr-smithers-excellent/docker-build-push@v6
            name: Build & push Docker image
            with:
              image: unknown/main
              registry: docker.io
              tags: v1, latest
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

            


